# anything.yaml


# optional: name of the workflow
name: anything

# ON EVENTS 
on:
  push: # push to the repository
    # branches:
    #   - main
    # paths:
    #   - '*.md'
#   pull_request: # pull request to the repository
  workflow_dispatch: # manual trigger of the workflow
#   schedule: # schedule the workflow to run at a specific time

# JOBS


jobs:
  Job_1:
    runs-on: ubuntu-latest  # RUNNER  VM == Runner  vm109ddcmwicsi
    steps:
        - name: checkout code # step 0
          uses: actions/checkout@v7 # action

        - name: ls the repo # step 0
          run: ls -la | grep README.md # command

        - name: Run a script # step 1
          run: echo "Hello, world!"  >> output.txt # command

        - uses: actions/upload-artifact@v7
          with:
            path: output.txt
            name: output.txt

        - name: read output.txt # step 2
          run: cat output.txt # command

        # - name: setup node # step 3
        #   uses: actions/setup-node@v7 # action







  Job_2:
    needs: Job_1
    runs-on: ubuntu-latest  # RUNNER  VM == Runner   vm=jjncwjcnwijn
    steps:
        - uses: actions/download-artifact@v8
          with:
            path: output.txt
            name: output.txt

        - name: ls the repo # step 0
          run: ls -la 

        - name: read output.txt # step 2
          run: cat output.txt # command
          continue-on-error: true

        - name: setup python # step 4
          uses: actions/setup-python@v7
          with:
            python-version: '3.13' 